version: '3'
name: shadow-pos-api
services:
  shadow-pos:
    container_name: SHADOW-POS
    image: shadow-pos
    ports:
      - 3000:3000
    environment:
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: pos
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
  db:
    container_name: POS-DB-API
    image: postgres:16.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./bd-data:/var/lib/postgresql/data
