version: '3'
name: postgresDB
services:
  db:
    container_name: POS-DB-API
    image: postgres:16.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./bd-data:/var/lib/postgresql/data
